version: '3.3'
services:
  sdc1:
    container_name: ${COMPOSE_PROJECT_NAME}_sdc1
    build:
      context: build/sdc1
      args:
        SDC_VERSION: $SDC_VERSION
    ports:
      - '18630:18630'
    volumes:
      - './host_volumes/host_data:/host_data'
      - './host_volumes/sdc1_user_libs:/opt/streamsets-datacollector-user-libs'
      - './host_volumes/sdc1_libs_extras:/opt/streamsets-datacollector-${SDC_VERSION}/streamsets-libs-extras'
      - './host_volumes/sdc1_libs_common_lib:/opt/streamsets-datacollector-${SDC_VERSION}/libs-common-lib'
      - 'sdc1_data:/data'
      - 'sdc1_conf:/etc/sdc'
      - 'sdc1_libs:/opt/streamsets-datacollector-${SDC_VERSION}/streamsets-libs'
    networks:
      sdc_net:
        ipv4_address: ${SDC1_IP}
    env_file:
      - .env
volumes:
  sdc1_data:
  sdc1_conf:
  sdc1_libs:
networks:
  sdc_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
